GET http://localhost:3001/

### Get Info
GET http://localhost:3001/info


### Get Persons
GET http://localhost:3001/api/persons

### Get Persons by id
GET http://localhost:3001/api/persons/661a1924ce804956b867cac5

### Delete Persons by id
DELETE http://localhost:3001/api/persons/661a193622ef23e494ee97df

### Post Persons by id
POST http://localhost:3001/api/persons
content-type: application/json
{
    "name": "Bismo",
    "number": "031-321321"
}

### Update Persons by id
PUT http://localhost:3001/api/persons/5
content-type: application/json
{
    "name": "Bisma",
    "number": "33333333"
}